pipeline:
  build-docker:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker ps
      - docker build -t new .
    when:
      event: [push]

