---
kind: pipeline
type: docker
name: build
steps:
  - name: Build docker image
    image: plugins/docker
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}    
    when:
      event:
        - push
